WITH 
ICD9_SUBSET AS (
  SELECT REPLACE (ICD9_CODE, ".", "") AS ICD9_CODE, LONG_TITLE
  FROM `hst-953-2019.bias2020.icd9_substance_abuse`
),
ABUSE_DIAGNOSES AS (
  SELECT SUBJECT_ID, HADM_ID, ICD9_CODE, LONG_TITLE
  FROM `physionet-data.mimiciii_clinical.diagnoses_icd`
  INNER JOIN ICD9_SUBSET
  USING (ICD9_CODE)
)

SELECT * 
FROM ABUSE_DIAGNOSES 
